version: '2'
services:
  conference11-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/conference11/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=conference11
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
